<?php

declare(strict_types=1);

namespace App\Application\Order\Command;

use App\Application\Order\DTO\CreateOrderItemDTO;
use App\Application\Order\DTO\CreateOrderResponseDTO;
use App\Domain\Order\Entity\Order;
use App\Domain\Order\Entity\OrderItem;
use App\Domain\Order\Repository\OrderRepositoryInterface;
use App\Domain\Order\Service\OrderNumberGenerator;
use App\Domain\Order\ValueObject\ContractorType;
use App\Domain\Order\ValueObject\OrderId;

final class CreateOrderHandler
{
    public function __construct(
        private readonly OrderRepositoryInterface $orderRepository,
        private readonly OrderNumberGenerator $orderNumberGenerator
    ) {
    }

    public function handle(CreateOrderCommand $command): CreateOrderResponseDTO
    {
        // Generate order numbers
        $orderNumbers = $this->orderNumberGenerator->generate();
        $orderNumber = $orderNumbers['orderNumber'];
        $uniqueOrderNumber = $orderNumbers['uniqueOrderNumber'];

        // Create order items
        $orderItems = array_map(
            fn (CreateOrderItemDTO $item) => new OrderItem($item->productId, $item->price, $item->quantity),
            $command->items
        );

        // Create order (ID will be generated by database)
        // Using a temporary ID of 0, will be replaced when saved
        $order = new Order(
            new OrderId(0),
            $orderNumber,
            $uniqueOrderNumber,
            $command->sum,
            ContractorType::fromInt($command->contractorType),
            false, // isPaid - new orders are not paid by default
            ...$orderItems
        );

        // Save order
        $this->orderRepository->save($order);

        return new CreateOrderResponseDTO(
            $uniqueOrderNumber->getValue()
        );
    }
}
